### ISSUE TITLE
Grails 1.3.9 download link is broken

### ISSUE THREAD

**Issue by yellowsnow** [grails/grails-static-website#17]
Hi,

The link for Grails 1.3.9 is broken on grails.org/download.html, could this be fixed please?
Is there an archive btw?

Cheers

**Comment by guramritpal-jft** [comment]
@jeffbrown  how to fix it. im interested.

**Comment by jeffbrown** [comment]
It looks like 1.3.9 didn't migrate to GitHub releases.  I am not sure why.  For now you can download it at http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-1.3.9.zip.

Thanks for the feedback.

**Comment by JasonTypesCodes** [comment]
The download link for 1.3.9 appears to be behaving as expected
