### ISSUE TITLE
Grails 1.2.0 relase bad created

### ISSUE THREAD

**Issue by ricardoul** [grails/grails-static-website#18]
Hello

The relase of 1.2.0 is bad created, should be https://github.com/grails/grails-core/releases/download/v1.2.0/grails-1.2.0.zip and is https://github.com/grails/grails-core/releases/download/v1.2/grails-1.2.0.zip

Thanks

**Comment by ManvendraSK** [comment]
@graemerocher I guess we should change the tags for 1.2 and 1.3 to 1.2.0 and 1.3.0 in github repo of grails-core. If we now do this then the download will work as the equivalent zip file is named as `grails-1.2.0.zip` and  `grails.1.3.0.zip`. Merely changing the `previousVersions` list in sitemap.groovy won't solve the problem.
Here is some code snippet for quick reference where `previousVersions` is defined and used:

#### sitemap.groovy
```groovy
// --- some code
def previousVersions = [
        '1.2.0', '1.2.1', '1.2.2', '1.2.3', '1.2.4', '1.2.5',
        '1.3.0', '1.3.1', '1.3.2', '1.3.3', '1.3.4', '1.3.5', '1.3.6', '1.3.7', '1.3.8', '1.3.9',
        '2.0.0', '2.0.1', '2.0.2', '2.0.3', '2.0.4',
        '2.1.0', '2.1.1', '2.1.2', '2.1.3', '2.1.4', '2.1.5',
        '2.2.0', '2.2.1', '2.2.2', '2.2.3', '2.2.4', '2.2.5',
        '2.3.0', '2.3.1', '2.3.2', '2.3.3', '2.3.4', '2.3.5', '2.3.6', '2.3.7', '2.3.8', '2.3.9', '2.3.10', '2.3.11',
        '2.4.0', '2.4.1', '2.4.2', '2.4.3', '2.4.4', '2.4.5', '2.5.0', '2.5.1',
        '3.0.0', '3.0.1', '3.0.3'
]
// --- some code
```

#### download.groovy
```groovy
// --- some code
select(class: 'form-control', onchange: "window.location.href='https://github.com/grails/grails-core/releases/download/v'+ this.value +'/grails-' + this.value + '.zip'") {
                                    option 'Select a version'
                                    distributions.each{ dist ->
                                       option "${dist.packages.first().version}"
                                    }
                                }
// --- some code
```

**Comment by JasonTypesCodes** [comment]
Closing this issue as Grails 1.2 is no longer being actively supported
