### ISSUE TITLE
Create a GithubAction to trigger manually a website rebuild

### ISSUE THREAD

**Issue by sdelamo** [grails/grails-static-website#291]
To have the ability to rebuild the website on demand without the need to doing a commit.

**Comment by Richardson-e** [comment]
Sergio del Amo Caballero Sergio we can manually rerun the workflow now. Do we need a new workflow that does something different?

**Comment by sdelamo** [comment]
a new workflow. see an example in the micronautpodcast repository. I think we have manual workflows there

**Comment by jeffscottbrown** [comment]
> a new workflow. see an example in the micronautpodcast repository. I think we have manual workflows there

FYI... The Micronaut Podcast repository is presently at https://github.com/micronaut-projects/micronautpodcast.

**Comment by jamesfredley** [comment]
We are able to do this via https://github.com/grails/grails-static-website/actions/workflows/publish.yml 

![image](https://github.com/user-attachments/assets/8f74844c-fe29-4b5a-815c-9e1787f3d9d2)
