### ISSUE TITLE
Javascript Error On Main Site

### ISSUE THREAD

**Issue by osscontributor** [grails/grails-static-website#317]
At https://grails.org/index.html I am seeing the following JS error logged as the page loads:

```
plugins.js:11 Uncaught TypeError: Cannot read properties of null (reading 'offsetTop')
    at plugins.js:11:59
```

![Screenshot 2024-02-19 at 12 52 00 PM](https://github.com/grails/grails-static-website/assets/15482/0aa64b63-7be8-4cb3-a2e8-2d829337a3ca)

**Comment by Richardson-e** [comment]
https://github.com/grails/grails-static-website/pull/319
