### ISSUE TITLE
Mixed content on documentation page

### ISSUE THREAD

**Issue by keeganwitt** [grails/grails-static-website#39]
http://grails.org/single-page-documentation.html loads fine, but https://grails.org/single-page-documentation.html does not render in Chrome or Firefox because of mixed content warning (http://docs.grails.org/latest/ was not over HTTPS).  Kinda annoying since the version Google links to is the HTTPS version.

I'm a backend guy, but I think you could just change `documentation.groovy` to use `https` instead of `http` in the links and just let the redirect happen.

**Comment by jeffbrown** [comment]
It appears this may no longer be an issue.  If it is please let us know.  Thanks for the feedback!
