### ISSUE TITLE
Common events calendar

### ISSUE THREAD

**Issue by sbglasius** [grails/grails-static-website#43]
I suggest that a website to manage events is to be made, that way event makers and conference organizers has one central place to maintain conferences related to Grails.

When I get around to it, I will start such initiative. This is a placeholder to see if there is any interest in the matter.

Also suggested for the Groovy Website: https://github.com/groovy/groovy-website/issues/93

**Comment by wiesej** [comment]
Thanks for the suggestion.  We have a calendar that lists upcoming events related to Grails, Groovy, and Micronaut.  Please see here https://grails.org/learning.html
