### ISSUE TITLE
Download combo box issue

### ISSUE THREAD

**Issue by rpalcolea** [grails/grails-static-website#44]
there is an empty option in the combo box that leads to https://github.com/grails/grails-core/releases/download/v/grails-.zip

<img width="872" alt="screen shot 2016-09-15 at 2 51 37 pm" src="https://cloud.githubusercontent.com/assets/1625920/18569248/4bfacf1c-7b56-11e6-864f-8bac55abc0f1.png">

also when you download an old version and select again ‘select version’ it takes you to https://github.com/grails/grails-core/releases/download/vSelect%20a%20version/grails-Select%20a%20version.zip (

**Comment by ilopmar** [comment]
Which browser and version are you using? I can't see the empty value:

![image](https://cloud.githubusercontent.com/assets/559192/18569523/6405bf66-7ba3-11e6-887f-f139e2908440.png)
