### ISSUE TITLE
Missing Grails versions 3.2.10 and 3.2.11 on download page

### ISSUE THREAD

**Issue by verglor** [grails/grails-static-website#67]
https://grails.org/download.html
![](https://i.imgur.com/lzvI03s.png)

**Comment by mattmoss** [comment]
Versions are sorted like strings... look between 3.2.2 and 3.2.1.

**Comment by verglor** [comment]
🤦‍♂️ Thank You.
But I think it's really confusing... I have totally overlooked them looking for the latest 3.2.x version.
