### ISSUE TITLE
Sort versions on download page lexicographically

### ISSUE THREAD

**Issue by verglor** [grails/grails-static-website#68]
Looking for the latest 3.2.x version [one easily overlook](https://github.com/grails/grails-static-website/issues/67) version 3.2.11 since it is down below 3.2.2 due to simple string sorting:
![](https://i.imgur.com/cfzZlb8.png)

**Comment by sdelamo** [comment]
Closed by https://github.com/grails/grails-static-website/commit/7d33ec37f4808676693fd2071f658ec3111c4620
