### ISSUE TITLE
[SECURITY] Grails Download page is HTTP by default

### ISSUE THREAD

**Issue by JLLeitschuh** [grails/grails-static-website#84]
Navigating from the homepage: https://grails.org/ and clicking on the 'Download' link brings you to:
http://grails.org/download.html

This page can be maliciously compromised to inject malicious scripts into the copy/paste sections:
http://thejh.net/misc/website-terminal-copy-paste

Solution: The Grails documentation site should only be available over HTTPS.

Also, the server should start responding with the `Strict-Transport-Security` header to ensure that browsers automatically connect to the HTTPS instance of the site.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security

Related: https://github.com/grails/grails-core/issues/11250

**Comment by jeffbrown** [comment]
https://github.com/grails/grails-static-website/blob/5d430493badcbc619f588673f17b0435813ce585/core/src/main/groovy/org/grails/pages/Page.groovy#L67 may be the issue.

**Comment by sdelamo** [comment]
Everything is now served as Https. Thanks for reporting @JLLeitschuh

**Comment by JLLeitschuh** [comment]
@sdelamo The site is still available over HTTP: http://grails.org/download.html

You should automatically redirect to HTTPS for all page requests.

**Comment by graemerocher** [comment]
@JLLeitschuh should be good now

**Comment by JLLeitschuh** [comment]
@graemerocher It's not. I just used a Chrome Incognito tab (IE: I have a clean browser cache) and the URL: http://grails.org/download.html does not redirect to https://grails.org/download.html

**Comment by graemerocher** [comment]
@JLLeitschuh it might tag a while to propagate the change to Github and/or be a browser caching issue. We have the "Enforce HTTPS" checkbox checked on Github which hosts these static pages
